[package]
name = "alpaca-dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
ascom-alpaca = { path = "../ascom-alpaca-rs", features = ["camera", "server"] }
async-trait = "0.1.64"
atomic = "0.5.1"
gphoto2 = { version = "3.2.0", features = ["test", "extended_logs"] }
image = "0.24.4"
ndarray = "0.15.6"
time = { version = "0.3.17", features = ["formatting"] }
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
