[package]
name = "alpaca-dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
ascom-alpaca-rs = { path = "./ascom-alpaca-rs" }
axum = "0.5.16"
tokio = { version = "1.21.2", features = ["rt", "macros"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[workspace]
members = ["ascom-alpaca-rs"]

[patch.crates-io]
serde_plain = { git = "https://github.com/RReverser/serde-plain", branch = "fix-serde-skip" }
