[package]
name = "alpaca-dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
ascom-alpaca-rs = { path = "./ascom-alpaca-rs", features = ["actix"] }
tracing-actix-web = "0.6.1"
tracing-subscriber = "0.3.16"

[workspace]
members = ["ascom-alpaca-rs"]
