[package]
name = "alpaca-dslr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-utils = "3.0.0"
actix-web = "4.2.1"
mime = "0.3.16"
serde = { version = "1.0.145", features = ["derive"] }
form_urlencoded = "1.1.0"
tracing-subscriber = "0.3.16"
tracing-actix-web = "0.6.1"
tracing = "0.1.37"
dashmap = "5.4.0"
serde_urlencoded = "0.7.1"
serde_json = "1.0.86"
futures-util = "0.3.24"
