[package]
name = "alpaca-dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
ascom-alpaca-rs = { path = "./ascom-alpaca-rs" }
axum = "0.5.16"
gphoto2 = { version = "2.0.0", features = ["test"] }
image = "0.24.4"
send_wrapper = "0.6.0"
tokio = { version = "1.21.2", features = ["rt", "macros"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
gphoto2_test = { git = "https://github.com/maxicarlos08/gphoto2-rs" }
net-literals = "0.2.0"

[workspace]
members = ["ascom-alpaca-rs"]
